### ISSUE TITLE
cdn.cvws.apple-dns.net

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#12]
Hi,
cdn.cvws.apple-dns.net is an Apple CDN (Content Delivery Network)
This is a domain that appears exclusively on your blocklist out of my 350+ blocklists. Where did you pull this domain from? (Just curious). If you'd like the link to my list of other blocklists for your validation, happy to share.

**Comment by hl2guide** [comment]
My consolidated list uses an aggressive approach to blocking that blocks most social media and privacy invading domains.

**Apple** is amongst them, **Microsoft** too. It also blocks time waster websites that hurt productivity.

For you specific situation please consider adding the below entries to AdGuard Home's __Custom filtering rules__:

```
@@||apple.com^$important
@@||icloud.com^$important
@@||apple-dns.net^$important
@@||pinterest.com^$important
```

(found in AdGuard Home's filters section)

That way my list can remain proactive and you can whitelist for your situation.
