### ISSUE TITLE
ICloud CDNs

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#16]
Hi,
Blocking a bunch of the Apple  iCloud CDNs
seems to be CNAMES for icloud-content.com 
defra.ce.apple-dns.net
edge-001.defra.ce.apple-dns.net
edge-003.usnyc.ce.apple-dns.net
edge-009.defra.ce.apple-dns.net
edge-010.gblon.ce.apple-dns.net
edge-012.defra.ce.apple-dns.net
edge-012.gblon.ce.apple-dns.net
edge-013.defra.ce.apple-dns.net
edge-014.gbman.ce.apple-dns.net
edge-017.defra.ce.apple-dns.net
edge-024.defra.ce.apple-dns.net
edge-024.gbman.ce.apple-dns.net
edge-031.gblon.ce.apple-dns.net
edge-032.gblon.ce.apple-dns.net
edge-035.usnyc.ce.apple-dns.net
edge-040.gblon.ce.apple-dns.net
edge-044.gblon.ce.apple-dns.net
edge-045.gblon.ce.apple-dns.net
gblon.ce.apple-dns.net
gbman.ce.apple-dns.net
searn.ce.apple-dns.net
usbos.ce.apple-dns.net
usnyc.ce.apple-dns.net

**Comment by hl2guide** [comment]
My consolidated list uses an aggressive approach to blocking that blocks most social media and privacy invading domains.

**Apple** is amongst them, **Microsoft** too. It also blocks time waster websites that hurt productivity.

For you specific situation please consider adding the below entries to AdGuard Home's __Custom filtering rules__:

```
@@||apple.com^$important
@@||icloud.com^$important
@@||apple-dns.net^$important
@@||pinterest.com^$important
```

(found in AdGuard Home's filters section)

That way my list can remain proactive and you can whitelist for your situation.
