### ISSUE TITLE
api.pinterest.com

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#17]
This is a CNAME for accounts.pinterest.com
Without it, Pinterest app does not work.

**Comment by hl2guide** [comment]
My consolidated list uses an aggressive approach to blocking that blocks most social media and privacy invading domains.

**Apple** is amongst them, **Microsoft** too. It also blocks time waster websites that hurt productivity.

For you specific situation please consider adding the below entries to AdGuard Home's __Custom filtering rules__:

```
@@||apple.com^$important
@@||icloud.com^$important
@@||apple-dns.net^$important
@@||pinterest.com^$important
```

(found in AdGuard Home's filters section)

That way my list can remain proactive and you can whitelist for your situation.
