### ISSUE TITLE
iCloud content servers

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#19]
Hi,
These are iCloud content servers, and blocking these kill icloud content.
p09-content.icloud.com 
p11-content.icloud.com 
p13-content.icloud.com 
p15-content.icloud.com 
p17-content.icloud.com 
p19-content.icloud.com 
p21-content.icloud.com 
p23-content.icloud.com 
p24-content.icloud.com 
p25-content.icloud.com 
p26-content.icloud.com 
p27-content.icloud.com 
p28-content.icloud.com 
p29-content.icloud.com 
p30-content.icloud.com 
p31-content.icloud.com 
p32-content.icloud.com 
p33-content.icloud.com 
p34-content.icloud.com 
p35-content.icloud.com 
p36-content.icloud.com 
p37-content.icloud.com 
p38-content.icloud.com 
p39-content.icloud.com 
p41-content.icloud.com 
p42-content.icloud.com 
p43-content.icloud.com 
p44-content.icloud.com 
p45-content.icloud.com 
p46-content.icloud.com 
p47-content.icloud.com 
p48-content.icloud.com 
p65-content.icloud.com

**Comment by hl2guide** [comment]
My consolidated list uses an aggressive approach to blocking that blocks most social media and privacy invading domains.

**Apple** is amongst them, **Microsoft** too. It also blocks time waster websites that hurt productivity.

For you specific situation please consider adding the below entries to AdGuard Home's __Custom filtering rules__:

```
@@||apple.com^$important
@@||icloud.com^$important
@@||apple-dns.net^$important
@@||pinterest.com^$important
```

(found in AdGuard Home's filters section)

That way my list can remain proactive and you can whitelist for your situation.
