### ISSUE TITLE
False Positive: time-ios.g.aaplimg.com

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#2]
This is a false positive I believe
Just needed for getting the time in IOS

**Comment by hl2guide** [comment]
hmmm ok, I'm not sure how to verify this since I have no apple devices.

**Comment by p1r473** [comment]
This domain seems to be exclusive to your blocklist, and none of the other 338 blocklists I am using are blocking this.

**Comment by p1r473** [comment]
https://support.apple.com/en-us/HT210060
time-ios.apple.com - Used by devices to set their date and time
This domain is a CNAME for this domain

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/82159911-ba1d0300-985f-11ea-85d1-5ad1d5b1cdc2.png)

**Comment by hl2guide** [comment]
This issue has been added to my next big update scheduled for July 2020.
