### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#20]
Hello,
typosquatting_blocklist.txt contains an invalid domain:  0ffcloud.com
Likely due to begining with the number 0

```
  [i] Target: https://raw.githubusercontent.com/hl2guide/DNS-Sinkhole-Lists-A2/master/typosquatting_blocklist.txt
  [✓] Status: Retrieval successful
  [i] Received 11195 domains, 1 domains invalid!
      Sample of invalid domains:
      - 0ffcloud.com
```

**Comment by hl2guide** [comment]
Thanks I'll fix that now.

**Comment by hl2guide** [comment]
Ref: https://abhijitrawool.com/valid-domain-name-characters/

**Comment by p1r473** [comment]
I am using PiHole. Its script thinks its an invalid domain
Perhaps one of the other characters in it are non-ASCII?
Maybe, you can type it out manually?

  [i] Target: https://raw.githubusercontent.com/hl2guide/DNS-Sinkhole-Lists-A2/master/typosquatting_blocklist.txt
  [✓] Status: Retrieval successful
  [i] Received 11195 domains, 1 domains invalid!
      Sample of invalid domains:
      - 0ffcloud.com
