### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by r2ixuz** [hl2guide/Filterlist-for-AdGuard#21]
Please don't block nameservers like "ns[1-4].msft.net" . These are among others for Microsoft domains responsible.

And why do you block "us.gov" ? Makes also no sense to me...

**Comment by hl2guide** [comment]
This list contains the NSA Blocklist therefore us.gov is blocked. Please whitelist that if needed.

I'll consider the handling "ns[1-4].msft.net" domains.
