### ISSUE TITLE
Use of proper syntax for extra protection and compability reasons.

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [hl2guide/Filterlist-for-AdGuard#24]
Examples:

||google.com^ instead of google.com to block google and all its subdomains.

**/**((^)|(.))telemetry.**/** instead of ((^)|(.))telemetry. otherwise the REGEX rule simply doesn't work.

For allowlist: login.live.com or ||login.live.com^ instead of @@||login.live.com^$important

Adguard home automatically whitelists all the domains enrolled in DNS allowlist, rendering the @@ syntax redundant.

**Comment by hl2guide** [comment]
hmm, that runs mostly counter to the advice that I got from an AdGuard support email from 2 months ago. I think AdGuard Home is smart enough for this to not be an issue.
