### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by e-ct** [hl2guide/Filterlist-for-AdGuard#27]
Hi,

Can you please adjust this document?

filter_whitelist.txt

Could you please add two kinds of content?

Title: Filter whitelist for AdGuard 2.2

`@@||s.yimg.com^$important`

@hl2guide

**Comment by hl2guide** [comment]
I'll consider it, yahoo.com is really a sun-setting search engine that isn't that popular anymore.

I'd be more concerned about privacy issues with them personally.
