### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by Nicehack25** [hl2guide/Filterlist-for-AdGuard#28]
google.c   rule blocking all google services , even google search, please could you remove this rule?
![Screenshot 2020-10-29 012036](https://user-images.githubusercontent.com/26417104/97507042-0333c000-1985-11eb-90c7-06f2a7e42197.png)

**Comment by hl2guide** [comment]
Seems to me to be an issue just for your region since for me it loads **google.com** and **hangouts.google.com** just fine.

Are you visiting google.com?

**Comment by Nicehack25** [comment]
No, i could visit only if add custom rules in adguard

**Comment by 91ajames** [comment]
Might be some adlist blocker your using, i thought too that this was blocking me as well but there was something in my adlist blocking it from my side that I am also using. 

Great Job on this Project!

**Comment by Nicehack25** [comment]
I started experimenting with it and found that adding this rule to custom rules solve all problems.
Just add this:      @@||google.c$important

**Comment by 91ajames** [comment]
Also to let you know unless due to privacy and pin location but the weather app on windows 10 is broken.
Was unable to update it. 

tile-service.weather.microsoft.com

**Comment by Chreece** [comment]
I have the same problem, the AIO blocklist blocks all domains from google.com and also google.de for me

**Comment by Nicehack25** [comment]
> I have the same problem, the AIO blocklist blocks all domains from google.com and also google.de for me

In your way will help this rule: @@||google.d$important  and @@||google.c$important

**Comment by 91ajames** [comment]
Reasons I edited and suggested to eradicate google entirely bc I included that factor. 
To many google urls and other scenario's to create constant problems from this list to save people's time.

I think there's a L in there like google.de is.

**Comment by Nicehack25** [comment]
> Reasons I edited and suggested to eradicate google entirely bc I included that factor.
> To many google urls and other scenario's to create constant problems from this list to save people's time.
> 
> I think there's a L in there like google.de is.

I agree with you. it is just a quick fix way.

**Comment by 91ajames** [comment]
Some how, http://google.nl/ and http://google.ln/ (both L's) went throu which means they weren't in this list.
So something in this list is blocking certain google domains unintentional.

But after that, I don't know much of the other domains.

**Comment by hl2guide** [comment]
Thanks for all the feedback on this, I'll review the list and see what's going on.

Please all check that you have:
* Upgraded AdGuard Home to the latest version (0.104.0)
* Added the blocklist to AdGuard Home
* Added the allowlist to AdGuard Home

To be clear after all my testing (from Australia) as of yet I've failed to reproduce the reported blocking of Google domains.

**Comment by hl2guide** [comment]
I'm going to the remove the rule "google.c" in the next generated AIO list.
