### ISSUE TITLE
ebay

### ISSUE THREAD

**Issue by andekande** [hl2guide/Filterlist-for-AdGuard#29]
can't access ebay.com or my local ebay.de

`
Rule: slot9428.ebay.com.edgekey.net
`
`
Origin Reply:
CNAME: slot9428.ebay.com.edgekey.net. (ttl=296)
CNAME: e9428.a.akamaiedge.net. (ttl=21596)
A: 104.81.141.113 (ttl=16)
`

**Comment by hl2guide** [comment]
Thanks for reporting this.

Please add the following to AdGuard's "Custom filtering rules":

`@@||www.ebay.com^$important`
`@@||srv.de.ebayrtm.com^$important`
`@@||secureir.ebaystatic.com^$important`
`@@||ir.ebaystatic.com^$important`
`@@||www.ebay.de^$important`


 I'll add them to the whitelist if you have further **ebay** access issues.

**Comment by andekande** [comment]
Actually srv.de.ebayrtm.com is a tracker address. I now use these rules to have ebay work properly and be able to offer products:
`@@||www.ebay.com^$important`
`@@||secureir.ebaystatic.com^$important`
`@@||securepics.ebaystatic.com^$important`
`@@||secureinclude.ebaystatic.com^$important`
`@@||vi.vipr.ebaydesc.com^$important`
`@@||vi.raptor.ebaydesc.com^$important`
`@@||www.ebay.de^$important`
