### ISSUE TITLE
False Positive: world-gen.g.aaplimg.com

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#3]
I believe this domain is a false positive. I think it is required for Apple updates.

**Comment by hl2guide** [comment]
hmmm ok, I'm not sure how to verify this since I have no apple devices.

**Comment by p1r473** [comment]
@hl2guide  Where did you find this domain? I am using over 300+ blocklist and this domains (and the other one I reported) are not on any other blocklist.

**Comment by hl2guide** [comment]
This issue has been added to my next big update scheduled for July 2020.

**Comment by p1r473** [comment]
This is a CNAME for developer.apple.com
![image](https://user-images.githubusercontent.com/9235633/82682590-7f2f1c80-9c1d-11ea-9952-1b71ef352e0a.png)
