### ISSUE TITLE
whitelist the .fr domain

### ISSUE THREAD

**Issue by awalo666** [hl2guide/Filterlist-for-AdGuard#32]
your list block all the domain that finish with .fr why?
My main language is french and this cause alot of website to be broken and i was waiting in hope but nothing change so that why i open this issue. 

But for the rest keep your good work i love your list

**Comment by hl2guide** [comment]
This list uses zone blocking so yes some country specific zones are defined.

For you I suggest adding:
`@@||.fr^$important`

or even better individual .fr sites.

to Adguard's Custom filtering rules.

Domains can easily be unblocked in Aguard's **Query Log**.
