### ISSUE TITLE
Suggestions for version 2.4?

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/Filterlist-for-AdGuard#33]
I'd love to hear your suggestions for version 2.4.

Any new lists you'd like to suggest?

**Comment by 91ajames** [comment]
Not sure the exact location uBlock plugin in firefox gets there stuff from but been adding a few manually from them.
||livesegmentservice.com^$3p
||unid.go.com^$3p
||msn.com###onetrust-banner-sdk^important
#||msn.com###onetrust-banner-sdk > div.ot-sdk-container > div.ot-sdk-row
||msn.com###onetrust-consent-sdk^important
||amazonaws.com/ki.js/
||beacon.wikia-services.com^

altho msn doesn't work, gathered from adguard plugin to manually block it.
consent cookie popup with grey screen. I could still scroll and read without blocking it.

**Comment by hl2guide** [comment]
Thanks for the feedback!

A lot of those are cosmetic filters (rules that only apply in adblockers).

_For this situation I'd be asking for plain domain lists._

**Comment by 91ajames** [comment]
Totally slipped my mind. Np.

Figuring out how to whitelist parts of cnn and there videos.
Fixed the picture per video (@@||cdn.cnn.com) but having the player pop up to play/select timeline of the video and change the selection from one video to the next is another issue. Not sure its from you, mostly blaming one of my list for pi-hole.

**Comment by 91ajames** [comment]
ps, looks like he may be shutting down filterlist.
https://hub.filterlists.com/t/hub-shutdown-end-of-2020/105

**Comment by hl2guide** [comment]
Version 2.4 is on it way, I've created a second internal beta that I'm testing now.

It should release publicly within one week if testing passes.

**Comment by hl2guide** [comment]
I'm currently generating 2.4 right now.
