### ISSUE TITLE
video feed. - CNN & The Weather Channel

### ISSUE THREAD

**Issue by 91ajames** [hl2guide/Filterlist-for-AdGuard#34]
One for [cnn](https://www.cnn.com/2020/11/10/tech/ring-doorbell-recall-fire/index.html) which i figured out the pictures comes from `cdn.cnn.com`
Other from [weather channel](https://weather.com/news/news/2020-11-17-hurricane-iota-impacts-nicaragua-colombia-honduras-central-america), pictures from `s.w-x.co`. player looks like its coming from ssl.p.jwpcdn.com but errors out, firfox says it works while edge says it doesn't, not sure its a fluke on my end.
Unable to figure out for the player to pop up and play. Any ideas what I can, to whitelist?
Keep up the Great Work!

**Comment by hl2guide** [comment]
Since I don't use CNN or Weather Channel for privacy reasons, I suggest that you check AdGuard's query log and whitelist domains that are blocked after pages are loaded.
