### ISSUE TITLE
Reporting Blocked Popular Domains

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/Filterlist-for-AdGuard#35]
Please comment below to report major/popular domains that are blocked in the **AIO list**.

I'm looking for only popular major sites: e.g:
- ibm.com
- intel.com
- nike.com
- etc..

**Comment by groninge01** [comment]
- outlook.office.com
- spotify.com
- instagram.com
- pinterest.com
- images-eu.ssl-images-amazon.com
- facebook.com

**Comment by hl2guide** [comment]
> * outlook.office.com
> * spotify.com
> * instagram.com
> * pinterest.com
> * images-eu.ssl-images-amazon.com
> * facebook.com

Added some to whitelist, excluding social media networks (still blocked by default).

**Comment by groninge01** [comment]
- reebok.com
- reebok.nl

**Comment by 91ajames** [comment]
@hl2guide perhaps we should keep this open for discussion?

Discovered two links for pininterest I think should be added. no pictures loaded and no pic-feed/video would play on the app.
@@||i.pinimg.com
@@||v.pinimg.com

I have also blocked these in blacklisted and have tested it out incase that breaks anything. picture and video displays fine.

CNAME: i.pinimg.com.gslb.pinterest.com. (ttl=9)
CNAME: 2-01-37d2-0004.cdx.cedexis.net. (ttl=9)
CNAME: dualstack.pinterest.map.fastly.net. (ttl=9) 

CNAME: v.pinimg.com.gslb.pinterest.com. (ttl=3298)
CNAME: 2-01-37d2-0007.cdx.cedexis.net. (ttl=30)
CNAME: v.pinimg.com.edgekey.net. (ttl=298)
CNAME: e6449.dsce2.akamaiedge.net. (ttl=30) 

Just a suggestion. ;)

Also notice s.pinimg from one of my other blocklist, unsure what that is but i had kept it block.
