### ISSUE TITLE
New Host list

### ISSUE THREAD

**Issue by Stright** [hl2guide/Filterlist-for-AdGuard#37]
### List
https://gitlab.com/Shub_/mobile-ads-block/-/raw/master/list

### What does it do?
It's the ultimate list to block ads, trackers and malware for mobile devices, it has minimal false positives aswell.

**Comment by hl2guide** [comment]
Thanks for the recommendation, I'll review it over December.

That list is currently not formatted for AdGuard e.g.:

```
!---------------------------------------
! LOCAL HOST
!---------------------------------------
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

So you may like to contact the repo owner at GitLab and request a version that is formatted for AdGuard.
