### ISSUE TITLE
Other Host List

### ISSUE THREAD

**Issue by 91ajames** [hl2guide/Filterlist-for-AdGuard#38]
Looking back on my old pihole of the list I had on there that some few I already posted or some already added. 
For any other suggestions to be added for the next version.

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/unwanted-iranian.txt
https://anti-ad.net/easylist.txt
https://280blocker.net/files/280blocker_domain.txt
https://raw.githubusercontent.com/yous/YousList/master/hosts.txt
https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuardHome.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt
https://abpvn.com/android/abpvn.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list
https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
https://someonewhocares.org/hosts/zero/hosts
https://raw.githubusercontent.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter-Web.txt
https://raw.githubusercontent.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter.txt
https://filters.adavoid.org/ultimate-ad-filter.txt
https://easylist.to/easylist/fanboy-annoyance.txt
https://filters.adavoid.org/ultimate-privacy-filter.txt
https://filters.adavoid.org/filters/FanboysSocialBlockingList.txt
https://filters.adavoid.org/ultimate-security-filter.txt
https://filters.adavoid.org/filters/Spam404.txt
https://filters.adavoid.org/filters/NoCoin.txt
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://urlhaus.abuse.ch/downloads/hostfile/
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://filtri-dns.ga/filtri.txt
https://v.firebog.net/hosts/Easylist.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://infosec.cert-pa.it/analyze/listdomains.txt
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://phishing.army/download/phishing_army_blocklist_extended.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://dbl.oisd.nl/
https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt	
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
https://www.malwaredomainlist.com/hostslist/hosts.txt	
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list	
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt	
https://block.energized.pro/assets/sources/filter/malwaredomainlist.com.txt (i still have the latest copy before it was erased, active but empty)
https://blocklistproject.github.io/Lists/tracking.txt
https://blocklistproject.github.io/Lists/scam.txt
https://blocklistproject.github.io/Lists/redirect.txt
https://blocklistproject.github.io/Lists/ransomware.txt
https://blocklistproject.github.io/Lists/phishing.txt
https://blocklistproject.github.io/Lists/malware.txt
https://blocklistproject.github.io/Lists/fraud.txt
https://blocklistproject.github.io/Lists/crypto.txt
https://blocklistproject.github.io/Lists/ads.txt
https://blocklistproject.github.io/Lists/abuse.txt
http://sysctl.org/cameleon/hosts.win
https://raw.githubusercontent.com/passel/pihole-blocklists/master/ads.txt
https://raw.githubusercontent.com/passel/pihole-blocklists/master/malware-malicious.txt
https://raw.githubusercontent.com/passel/pihole-blocklists/master/scam-spam.txt
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt	
https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt	
https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
https://raw.githubusercontent.com/imkarthikk/pihole-facebook/master/pihole-facebook.txt	
https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Facebook/facebookblocklist.txt	
https://raw.githubusercontent.com/einyx/pihole-blocklist/master/facebook.txt	
https://raw.githubusercontent.com/imkarthikk/pihole-facebook/master/pihole-whatsapp.txt	
	
	

Some other ones that i have that are no longer up

http://0.0.0.0/host-file/a-tv-samsung.txt	
http://0.0.0.0/host-file/KitsapCreator-pihole_blocklist-ads.txt	
http://0.0.0.0/host-file/KitsapCreator-pihole_blocklist-malware_malicious.txt	
http://0.0.0.0/host-file/list_browser_UBO.txt	
http://0.0.0.0/host-file/zeustracker.abuse.ch.blocklist.txt
http://0.0.0.0/host-file/hosts-file-net-ad_servers.txt
http://0.0.0.0/host-file/hosts-file-net-emd.txt
http://0.0.0.0/host-file/hosts-file-net-exp.txt
http://0.0.0.0/host-file/hosts-file-net-fsa.txt	
http://0.0.0.0/host-file/hosts-file-net-grm.txt
http://0.0.0.0/host-file/hosts-file-net-hjk.txt
http://0.0.0.0/host-file/hosts-file-net-mmt.txt	
http://0.0.0.0/host-file/hosts-file-net-pha.txt	
http://0.0.0.0/host-file/hosts-file-net-pup.txt	
http://0.0.0.0/host-file/malwaredomainlist.com.block-energizer-pro-filter.txt
http://0.0.0.0/host-file/Akamaru-PiHoleList-smarttv.txt - depends

**Comment by hl2guide** [comment]
Thanks for the list 👍

**Comment by 91ajames** [comment]
@hl2guide Np.
also missed host-file-net-psh in there and another malware domain list. incase you want to take a look throu.

[Akamaru-PiHoleList-smarttv.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691419/Akamaru-PiHoleList-smarttv.txt)
[hosts-file-net-ad_servers.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691421/hosts-file-net-ad_servers.txt)
[hosts-file-net-emd.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691423/hosts-file-net-emd.txt)
[hosts-file-net-exp.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691425/hosts-file-net-exp.txt)
[hosts-file-net-fsa.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691426/hosts-file-net-fsa.txt)
[hosts-file-net-grm.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691427/hosts-file-net-grm.txt)
[hosts-file-net-hjk.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691428/hosts-file-net-hjk.txt)
[hosts-file-net-mmt.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691429/hosts-file-net-mmt.txt)
[hosts-file-net-pha.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691430/hosts-file-net-pha.txt)
[hosts-file-net-psh.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691431/hosts-file-net-psh.txt)
[hosts-file-net-pup.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691432/hosts-file-net-pup.txt)
[KitsapCreator-pihole_blocklist-ads.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691433/KitsapCreator-pihole_blocklist-ads.txt)
[KitsapCreator-pihole_blocklist-malware_malicious.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691434/KitsapCreator-pihole_blocklist-malware_malicious.txt)
[list_browser_UBO.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691435/list_browser_UBO.txt)
[malwaredomainlist.com.block-energizer-pro-filter.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691436/malwaredomainlist.com.block-energizer-pro-filter.txt)
[malwaredomainlist.com.hostlist.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691437/malwaredomainlist.com.hostlist.txt)
[mmotti_adguard-home-filters_custom-subscriptions-github-filters.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691438/mmotti_adguard-home-filters_custom-subscriptions-github-filters.txt)
[mmotti_adguard-home-filters_custom-subscriptions-github-regrex.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691439/mmotti_adguard-home-filters_custom-subscriptions-github-regrex.txt)
[zeustracker.abuse.ch.blocklist.txt](https://github.com/hl2guide/Filterlist-for-AdGuard/files/5691440/zeustracker.abuse.ch.blocklist.txt)

for LG, these are needed to use for mic/apps/pictures content store
`#Smart-TV`
@@||aic-ngfts.lge.com `#don't remember`
@@||ngfts.lge.com `#i believe this was to download and updates the apps`
@@||us.lgtvsdp.com `#mic feature on the remote and other info like asking the weather, seen a few places blocking this.`
@@||us.rdx2.lgtvsdp.com `#don't remember`
@@||us.info.lgsmartad.com `uses the pictures in the store` `not sure about other apps with ads using this`
