### ISSUE TITLE
bestbuy purchase email

### ISSUE THREAD

**Issue by 91ajames** [hl2guide/Filterlist-for-AdGuard#39]
**Describe the bug**
click.emailinfo2.bestbuy.com

**To Reproduce**
Talking with an agent to price match from another store and then purchase that item via sent by email, clicking view order status hits this link which is blocked to purchase.

**Expected behavior**
click.emailinfo2.bestbuy.com > bestbuy.com

**Screenshots**
After whitelisting `@@||click.emailinfo2.bestbuy.com`
![2020-12-16 (1)](https://user-images.githubusercontent.com/24540531/102393008-d1fb6780-3fa5-11eb-9561-7347b4003252.png)

**Desktop (please complete the following information):**
- Browser firefox
- Version 83.0

**Comment by hl2guide** [comment]
If the original URL is just a redirector then you can use the rule:
`@@||click.emailinfo*.bestbuy.com`
