### ISSUE TITLE
PGA Tour 21 PS4 Breaks

### ISSUE THREAD

**Issue by 91ajames** [hl2guide/Filterlist-for-AdGuard#40]
**Describe the bug**

PGA Tour 21 PS4 Game will be broken without white listing this link.
telemetry.api.2kcoretech.online

Here's the weird part, disconnecting the ps4 system, you be able to get passed the start menu to access the main menu except you can't do any live features from playstation. When I re-hook the ethernet while the game is on, in the main menu, the game gets notified with the games signia at the bottom right corner, then the game gets unresponsive out of the blue. You can see the particles fly due to being a sports EA game but the game gets halted for whatever reason that this telemtry link does to this game. I can't explain why it needs it so desperately that this will cause the game to brake. The normal function's outside the game of the playstation OS works fine. Just that this game is a total dud if your connected to your internet while this is blocked. Game is brand new and sealed that came in the mail.

I have no idea if this is the same case for the xBox.

I don't know how many people would use this great filterlist but I just liked this info out to be known of this very weird issue.

_@@||telemetry.api.2kcoretech.online_

_you may close this_

ps.. telemetry would load this one next, tested it out by blocking it as well which makes the game a dud still.
_entitlements.api.2kcoretech.online_

**Comment by hl2guide** [comment]
Yep this doesn't surprise me at all. This list is really aggressive and there's considerations I've made like preferring privacy over convenience.

'telemetry' is the issue here and the fact that the game doesn't work without telemetry is pretty telling at questionable design.
