### ISSUE TITLE
Github does not open while the filter is active.

### ISSUE THREAD

**Issue by Serdar006** [hl2guide/Filterlist-for-AdGuard#42]
I don't know the source of the problem. :/

I would be happy if anyone with an idea wrote an answer.

**Comment by hl2guide** [comment]
Could you please read some details from your AdGuard's Query Log?
(hover question mark icon in Response column)

Are you using any other lists?

**Comment by Serdar006** [comment]
It's not just the Github page.

It doesn't open other pages either.
I just use this filter.

![Ekran Alıntı67sı](https://user-images.githubusercontent.com/77700853/105135433-11ffbe00-5b01-11eb-8771-4159eb0e9883.PNG)
![Ekrn Alıntısı](https://user-images.githubusercontent.com/77700853/105135446-19bf6280-5b01-11eb-9593-33fc5f5948f8.PNG)
![Ekran Alınt2ısı](https://user-images.githubusercontent.com/77700853/105135376-fac0d080-5b00-11eb-9559-9715a036c2bf.PNG)
![E2kran Alıntısı](https://user-images.githubusercontent.com/77700853/105135382-001e1b00-5b01-11eb-8147-64b3f850e1d2.PNG)
![Ekran Alıntı5sı](https://user-images.githubusercontent.com/77700853/105135418-0c09dd00-5b01-11eb-8447-51bff9dc42b0.PNG)
![Ekran A4lıntısı](https://user-images.githubusercontent.com/77700853/105136114-2f815780-5b02-11eb-9a38-e1f2b8ade2f9.PNG)

**Comment by hl2guide** [comment]
Okay, I can't replicate that issue on my end.

I suggest that you:

1. Check your AdGuard settings for misconfiguration
2. Check that you've added the allowlist too (https://github.com/hl2guide/Filterlist-for-AdGuard#allowlist-)
3. Try restarting your PC, if needed
