### ISSUE TITLE
New Host List

### ISSUE THREAD

**Issue by DevShubam** [hl2guide/Filterlist-for-AdGuard#43]
## Summary
This blocks IP Loggers, keeping you safe. 
### Blocklist Homepage
https://github.com/DevShubam/Blockd-IP-Loggers
### Blocklist Link
https://raw.githubusercontent.com/DevShubam/Blockd-IP-Loggers/master/uBlock_or_AdGuard.txt

**Comment by hl2guide** [comment]
Thanks for suggesting this 👍
