### ISSUE TITLE
Stryd.com not harmful site been blocked

### ISSUE THREAD

**Issue by Chreece** [hl2guide/Filterlist-for-AdGuard#51]
**Describe the bug**
www.stryd.com been blocked
**To Reproduce**
1. Go to www.stryd.com
2. See error

**Expected behavior**
Shouldn't not be blocked, not a harmful site (tech company who sells footpods for runners, need to get in the platform)

**Screenshots**

**Desktop (please complete the following information):**
- chrome
- latest

**Additional context**

**Comment by hl2guide** [comment]
Please double check that it's not working for you, it's loading for me:

![image](https://user-images.githubusercontent.com/17044982/109375243-7e938700-790f-11eb-9820-ff74347d6f0d.png)

If so please screenshot your Adguard Log.

**Comment by Chreece** [comment]
It's working, I don't know yet what caused the problem...
thanks for your time
