### ISSUE TITLE
Using the wrong filter

### ISSUE THREAD

**Issue by DevShubam** [hl2guide/Filterlist-for-AdGuard#52]
Hi!

This filterlist is using https://dbl.oisd.nl/, but according to the maintainer of the filter https://abp.oisd.nl should be used for AdGuard products. The dbl version is made for Pi-Hole. 

Please reply if you have any further questions :)

**Comment by hl2guide** [comment]
Thanks for the heads up, I checked and that is a fine format for this purpose. 👍

It's just a list of domains so that works great with matching potential duplicates.
