### ISSUE TITLE
Blocks almost every website

### ISSUE THREAD

**Issue by phildev4** [hl2guide/Filterlist-for-AdGuard#54]
**Describe the bug**
Blocks basically every website
**To Reproduce**
1. Go to 'teams.office.com'
**Expected behavior**
Gets blocked from blocklist 3
This is a problem with a lot of websites

**Comment by phildev4** [comment]
duckduckgo and github also get blocked.  Kind of ironic since this is hosted on github

**Comment by hl2guide** [comment]
I can load up all 3 fine:

- https://duckduckgo.com
- https://github.com
- teams.office.com

Please check your query log for the cause.
