### ISSUE TITLE
Top level domains are blocked

### ISSUE THREAD

**Issue by ninhnq** [hl2guide/Filterlist-for-AdGuard#55]
**Describe the bug**
There are top level domains which are blocked, eg: lifehacker.com
**To Reproduce**
1. Go to lifehacker.com
2. See error
**Expected behavior**
The filter should only block the harmful part (second level domain) of the site. eg. ad.lifehacker.com or stat.lifehacker.com ..
***Additional context**
zaloapp.com
tmall.com
1688.com
taobao.com
facebook.com
embedly.com
goo.gl
smarthomebeginner.com
atom.io
whatsapp.com
riotgames.com
amazon.com
chotot.com

**Comment by hl2guide** [comment]
Please red the README for this repo. This should be expected.
