### ISSUE TITLE
homebrew gets blocked

### ISSUE THREAD

**Issue by phildev4** [hl2guide/Filterlist-for-AdGuard#56]
**Describe the bug**
hombrew(macos packet manager) gets blocked
**To Reproduce**
1. Try to download things with homebrew
**Expected behavior**
Cant connec
**How to solve**
add @@||homebrew.bintray.com^$important to whitelist

**Comment by hl2guide** [comment]
Thanks for reporting this but please just manually whitelist this.

In the future please only report popular websites that are not a niche case.

**Comment by phildev4** [comment]
Okay didn't know that. Thanks for the fast response (:
