### ISSUE TITLE
new addition for filtersToIgnore: aom

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard#59]
**Describe the bug**
Filterlist 1, at line 1326127, has a rule which is simply:
`aom`

This blocks any response which contains the letters aom.

An example of a site this rule breaks is `apsjobs.gov.au`, which returns a result:
`CNAME www.apsjob.gov.au.00d5m0000008aomeay.live.siteforce.com`

**Possible solution**
This rule should be excluded with an update to your filtersToIgnore list with the rule:
`filtersToIgnore.append('aom')`

Also wish I could figure out where you store the filtersToIgnore in your Github code, so I could just make a change for you in a fork and submit a pull request.

**Comment by hl2guide** [comment]
Thanks for letting me know, I've added it and the next commit will have the fix applied.

I intentially do not add all source files as it could lead to the lists becoming unavilable at all due to too much traffic from other users.

**Comment by twcau** [comment]
> I intentially do not add all source files to GitHub as it could lead to the lists becoming unavilable at all due to too much traffic from other users.

Good to know, and thanks.

**Comment by hl2guide** [comment]
I added some logic to ignore lines that don't contain a dot.

This removes junk lines that contain only characters.
