### ISSUE TITLE
Whitelist recommendation: gateway.fe.apple-dns.net

### ISSUE THREAD

**Issue by twcau** [hl2guide/Filterlist-for-AdGuard#60]
**Describe the bug**
Blocking of the domain `gateway.fe.apple-dns.net` prevents iOS devices from backing up to iCloud.

This rule is currently contained within Blocklist 2, line 1370049.

**To Reproduce**
Two weeks of devices not being able to backup, proxying the traffic, and seeing what AdGuard was saying wasn't allowed, then permitting each one in custom filtering rules to find the culprit.

**Comment by hl2guide** [comment]
It's strange that you cannot simply read the Adguard Home query log.

I have no Apple products of any kind so me testing this is near impossible.

I'll add the item to the whitelist too.

**Comment by twcau** [comment]
> It's strange that you cannot simply read the Adguard Home query log.
> 
> I have no Apple products of any kind so me testing this is near impossible.
> 
> I'll add the item to the whitelist too.

I read the query log, but there was a bucket load of traffic to Apple at the time from the device when I was isolating.

And rather than just unblock everything and scattershot approach which could risk a list change that allows non essential traffic through, wanted to whittle it down to nothing more than the essential addresses.

Plus forces me to practice and learn a few more things too :)
