### ISSUE TITLE
Lithium sites

### ISSUE THREAD

**Issue by p1r473** [hl2guide/Filterlist-for-AdGuard#7]
Hello,
You are blocking some Lithium sites such as
dcvta86296.lithium.com which is a CNAME for community.microfocus.com
rogers.lithium.com which is a CNAME for communityforums.rogers.com
ppl.i.lithium.com which is a CNAME for www.paypal-community.com

I spoke to someone who had similar blocklists:
https://github.com/RooneyMcNibNug/pihole-stuff/issues/14
https://github.com/RooneyMcNibNug/pihole-stuff/issues/13
https://github.com/RooneyMcNibNug/pihole-stuff/issues/10

They said: 
> I think there has been some sort of domain change at some point. lithium.com seems to redirect to khoros.com now, which is the marketing site I'm looking for. I can't remember 100%, but maybe my enumeration got screwed up when I was taking a look at this marketing site a long time ago to add to my list.
> 
> For now, I have removed all of the lithium sites from my list in the following commit: 7323cd8
> 
> I will add some khoros.com URLs soon as well, fyi.

I think what has happened here is Lithium went through a domain change, and now these domains are benign and can be removed from the blocklist.

**Comment by hl2guide** [comment]
I expect in that case over time the included list will adjust that.

Thanks for reporting this.
