### ISSUE TITLE
Block more fake news websites

### ISSUE THREAD

**Issue by ninhnq** [hl2guide/Filterlist-for-AdGuard#76]
## Summary
Block more fake news websites e.g. which are pointed out by RationalWiki
### Basic example
Block the websites in this list: https://rationalwiki.org/wiki/List_of_websites_owned_by_Mike_Adams
### Motivation
Demote fake news and get a better chance for authenticated, trustworthy content in general.

**Comment by hl2guide** [comment]
Considering that this list is stopping at the end of September 2021 (see main readme) I'll close this issue and leave it here for other people.
